# Generated by Django 4.1.2 on 2023-02-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentClass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
