# Generated by Django 4.1.2 on 2023-02-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_years'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
    ]
