# Generated by Django 4.1.2 on 2023-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_year_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='part',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
