# Generated by Django 4.1.2 on 2023-02-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_year_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentClass',
        ),
        migrations.RemoveField(
            model_name='year',
            name='part',
        ),
        migrations.AddField(
            model_name='student',
            name='part',
            field=models.CharField(blank=True, choices=[('Mornig', 'Morning'), ('Evening', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.year'),
        ),
    ]
