# Generated by Django 4.1.2 on 2023-02-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_studentclass_remove_year_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='part',
            field=models.CharField(choices=[('Mornig', 'Morning'), ('Evening', 'Evening')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.year'),
            preserve_default=False,
        ),
    ]
