# Generated by Django 4.1.2 on 2023-02-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_student_part_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='part',
            field=models.CharField(max_length=20),
        ),
    ]
