# Generated by Django 4.1.2 on 2023-02-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_student_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
