# Generated by Django 4.1.2 on 2023-02-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessionYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sessionyear')),
                ('teacher', models.ManyToManyField(to='app.teacher')),
            ],
        ),
    ]
