# Generated by Django 4.1.2 on 2023-02-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
    ]
