# Generated by Django 4.1.2 on 2023-02-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_subject_teacher_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sessionYear',
            new_name='sessionYearID',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher',
            new_name='teacherID',
        ),
    ]
