# Generated by Django 4.1.2 on 2023-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
